Repository aquarist-labs/ceph, pull requests merged in 2023-06, with the labels that each got.

#153 rgw/sfs: Implement new versioning design
  qa/rgw/store/sfs/tests/fixtures/s3-tests.txt
  qa/rgw/store/sfs/tests/test-sfs-lifecycle-smoke.py
  qa/rgw/store/sfs/tests/test-sfs-object-locking.py
  qa/rgw/store/sfs/tests/test-sfs-versioning-smoke.py
  src/rgw/driver/dbstore/common/dbstore.h
  src/rgw/driver/sfs/CMakeLists.txt
  src/rgw/driver/sfs/bucket.cc
  src/rgw/driver/sfs/multipart.cc
  src/rgw/driver/sfs/object.cc
  src/rgw/driver/sfs/object.h
  src/rgw/driver/sfs/object_state.h
  src/rgw/driver/sfs/sfs_gc.cc
  src/rgw/driver/sfs/sqlite/bindings/blob.h
  src/rgw/driver/sfs/sqlite/conversion_utils.h
  src/rgw/driver/sfs/sqlite/dbconn.h
  src/rgw/driver/sfs/sqlite/objects/object_definitions.h
  src/rgw/driver/sfs/sqlite/sqlite_objects.cc
  src/rgw/driver/sfs/sqlite/sqlite_objects.h
  src/rgw/driver/sfs/sqlite/sqlite_versioned_objects.cc
  src/rgw/driver/sfs/sqlite/sqlite_versioned_objects.h
  src/rgw/driver/sfs/sqlite/versioned_object/versioned_object_conversions.cc
  src/rgw/driver/sfs/sqlite/versioned_object/versioned_object_conversions.h
  src/rgw/driver/sfs/sqlite/versioned_object/versioned_object_definitions.h
  src/rgw/driver/sfs/types.cc
  src/rgw/driver/sfs/types.h
  src/rgw/driver/sfs/user.cc
  src/rgw/driver/sfs/writer.cc
  src/test/rgw/sfs/compatibility_test_cases/columns_added.h
  src/test/rgw/sfs/compatibility_test_cases/columns_deleted.h
  src/test/rgw/sfs/compatibility_test_cases/optional_columns_added.h
  src/test/rgw/sfs/test_rgw_sfs_gc.cc
  src/test/rgw/sfs/test_rgw_sfs_sfs_bucket.cc
  src/test/rgw/sfs/test_rgw_sfs_sqlite_objects.cc
  src/test/rgw/sfs/test_rgw_sfs_sqlite_versioned_objects.cc
Labels: kind/enhancement, kind/quality

#155 rgw/testing: Add a few more passing s3tests
  qa/rgw/store/sfs/tests/fixtures/s3-tests.txt
Labels: area/tests, area/CI

#158 ci: Build crypto plugins openssl and isal
  qa/rgw/store/sfs/build-radosgw.sh
Labels: kind/feature, area/CI

#160 rgw/sfs: track db version, add metada upgrade path
  src/rgw/driver/sfs/sqlite/dbconn.cc
  src/rgw/driver/sfs/sqlite/dbconn.h
  src/test/rgw/sfs/CMakeLists.txt
  src/test/rgw/sfs/compatibility_test_cases/columns_added.h
  src/test/rgw/sfs/compatibility_test_cases/columns_deleted.h
  src/test/rgw/sfs/compatibility_test_cases/optional_columns_added.h
  src/test/rgw/sfs/test_rgw_sfs_metadata_compatibility.cc
Labels: area/rgw-sfs, kind/feature

#164 rgw/sfs: Remove redundant template code and make more flexible
  src/rgw/driver/sfs/sqlite/bindings/blob.h
  src/rgw/driver/sfs/sqlite/conversion_utils.h
Labels: kind/enhancement
