Repository aquarist-labs/ceph, pull requests merged in 2023-09, with the labels that each got.

#197 Better SQLite Profiling
  src/common/options/rgw.yaml.in
  src/rgw/driver/sfs/sqlite/dbconn.h
  src/rgw/rgw_perf_counters.cc
  src/rgw/rgw_perf_counters.h
  src/rgw/rgw_status_page.cc
Labels: area/rgw-sfs

#200 rgw/sfs: Conditional Copy Object
  qa/rgw/store/sfs/tests/fixtures/s3-tests.txt
  src/rgw/driver/sfs/object.cc
  src/rgw/driver/sfs/object.h
Labels: kind/feature

#157 Server Side Encryption Support
  qa/rgw/store/sfs/tests/fixtures/s3-tests.txt
  src/rgw/driver/sfs/multipart.cc
  src/rgw/driver/sfs/writer.cc
Labels: area/rgw-sfs, kind/feature

#195 Custom Metrics Support
  src/rgw/driver/sfs/sqlite/dbconn.cc
  src/rgw/driver/sfs/sqlite/dbconn.h
  src/rgw/rgw_appmain.cc
  src/rgw/rgw_sal_sfs.cc
  src/rgw/rgw_sal_sfs.h
  src/rgw/rgw_status_page.cc
  src/rgw/rgw_status_page.h
Labels: kind/enhancement, area/rgw-sfs

#196 GC Performance Counters
  src/rgw/driver/sfs/sfs_gc.cc
  src/rgw/rgw_perf_counters.cc
  src/rgw/rgw_perf_counters.h
  src/test/rgw/sfs/test_rgw_sfs_gc.cc
Labels: kind/enhancement, area/rgw-sfs

#203 CI Action: Build Image on PR label
  .github/workflows/build-image-on-pr-label.yaml
Labels: area/CI, ci/build-s3gw-image

#204 rgw/tests: Enable passing multipart s3tests
  qa/rgw/store/sfs/tests/fixtures/s3-tests.txt
Labels: kind/quality

#207 rgw/sfs: Send etag and correct mtime in copy object response
  qa/rgw/store/sfs/tests/test-sfs-copy-object.py
  src/rgw/driver/sfs/object.cc
Labels: kind/bug

#215 rgw/sfs: Fix multipart etag in response
  qa/rgw/store/sfs/tests/test-sfs-multipart.py
  src/rgw/driver/sfs/multipart.cc
Labels: kind/bug

#216 rgw/sfs: Calculate multipart etag based on its parts
  qa/rgw/store/sfs/tests/test-sfs-multipart.py
  src/rgw/driver/sfs/multipart.cc
Labels: kind/bug

#218 rgw/sfs: Fix GC gets stuck when deleting a bucket
  src/rgw/driver/sfs/sqlite/sqlite_multipart.cc
  src/test/rgw/sfs/test_rgw_sfs_gc.cc
Labels: kind/bug
